### ISSUE TITLE
Following a URL includes the trailing slash

### ISSUE THREAD

**Issue by nwl** [fluidinfo/loveme.do-chrome#111]
Current behaviour: I go to http://www.domain.com in my browser, open the sidebar and hit "Follow". The object that is created in FI is http://www.domain.com/ - including the trailing slash.

I get the impression there has been some discussion about this already but I think it's a saner default to strip trailing slashes from URLs when they are created as objects. Is there a reason to include it by default?

In the UI, I am more likely to search on a URL without the trailing slash. 

I know this is the tip of the iceberg for how we manage URL objects in general..

**Comment by jkakar** [comment]
This affects fluidinfo/infomaniac, too.

**Comment by terrycojones** [comment]
> Current behaviour: I go to http://www.domain.com in my browser, open the
> sidebar and hit "Follow". The object that is created in FI is
> http://www.domain.com/ - including the trailing slash.

Right. I guess you know why - the browser has gone to that URL because the one without the slash redirects to the one with the slash. The browser just doesn't show you the full URL.

> I get the impression there has been some discussion about this already

Yes, many times.

> but I think it's a saner default to strip trailing slashes from URLs when
> they are created as objects.

Just a clarifying note on this sentence - it's more accurate to say that tag values should be added to the object whose about value doesn't have the trailing slash.  That has to be done on each tag value addition (and removal). From the outside, one cannot know if an object (with an about value) already existed or not. I guess what I'm trying to say is not to think of it as object "creation" but of object use. Creation is one time, but use happens repeatedly and care has to be taken every time.

> Is there a reason to include it by default?

It's just that it makes things easier - like being able to use the browser's URL, to be able to follow URLs, not to have special cases, etc.

I agree it's better from a user POV not to have the trailing slash. I guess we should spend some time thinking about how we can do the stripping reliably.

In the browser extensions we could just send the stripped URL to the API and it would just work. There is code I'm working on now to follow URLs in tweets that could strip the final result (e.g. www.amazon.com redirects to www.amazon.com/).

One issue is that when a user selects a URL from the location bar in some browsers (Chrome, FF at least) the text selection includes the slash. So we could special case the browser extensions and the about box to strip trailing slashes from anything that looks like a URL. That limits what users of our UIs can look at, but not what programmers could do with the API - a tradeoff we've made in the past (with lowercase).

> In the UI, I am more likely to search on a URL without the trailing slash.

Yes, me too.

Anyone else have thoughts on this?  It's a bit of a pain internally for us, but, it seems, pretty simple and limited, and the issue for users (not that we have any) is a pretty bad one - e.g., comment on a URL in the extension and it doesn't show up when you go there in the OB. Of course now someone is going to suggest we also drop the 'http://' and 'https://'.  That way lies the empty string.
